# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc8c45a172dfb01170cf9f2cfd44d4789b170a2d6a0fb0cf270b80e55198cbf043d37d7f2dc4e59d7e4ab96361a6c992201022e69ddccd81910f99e604f495de

test:
  secret_key_base: 82be588e36a6077aaca2409c067926ebff1ac77aefc7745b1d7b0dd55ce5b6e7fc6e79ca640d81c2d0381dd4c038a5a0a5449df41e57a421ca4e477cc6286cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
